title: "競プロのための標準 C++"
summary: "◆ 内容\n競技プログラミングで使える C++ の主要な標準機能のサンプル付き解説を執筆しています。C++ のバージョンは AtCoder の gcc 12.2 に準拠した C++17 / 20 / 23 です。競技プログラミング固有のハックやスタイル（<bits/stdc++.h>, 大きな配列、using namespace std 等）の使用を避けているため、一般的な C++ ソフトウェア開発でも使える、また C++ 標準ライブラリの機能 (std:: から始まる) を意識したコーディングの練習ができます。\n\n◆ 対象読者\n・競プロ上達のために C++ 標準ライブラリを一通り学びたい方\n・コンテストで参照できる C++ ドキュメントを探している方\n・現時点ではとくに APG4b や市販入門書で C++ を学んだ人にとって有益な内容から書き始めています。将来的にはさらに幅広い内容を扱う計画です\n\n◆ 本書へのご意見・ご提案\nhttps://github.com/Reputeless/Zenn.Public/issues \n全編無料公開ですが、購入してくれると筆が進みます（これまで 30 人以上の方が購入してくれました。ありがとうございます）。\n\n◆ 著者の記事\n・競プロに便利な C++17 新機能まとめ\nhttps://qiita.com/Reputeless/items/db7dda0096f3ae91d450\n・ゲーム開発者のための C++11〜C++20 (共著)\nhttps://zenn.dev/tetsurom/books/cpp11-cpp20-for-game-developers\n・競プロ典型 90 問 練習 (C++17) https://github.com/Reputeless/tenkei_90\n・USACO (USA Computing Olympiad) コンテスト参加ガイド\nhttps://qiita.com/Reputeless/items/537b90150a56643750aa\n・冒険で学ぶ はじめてのプログラミング\nhttps://gihyo.jp/book/2018/978-4-7741-9918-4\n・C++ の歩き方 | cppmap\nhttps://cppmap.github.io/"
topics: ["cpp", "競プロ", "競技プログラミング", "atcoder"] # トピック（5つまで）
published: true # falseだと下書き
price: 800
chapters:
  - string
  - string-functions
  - vector
  - numeric
  - unordered_set
  - library-algorithm
  - library-tuple
  - library-ios-iomanip
  - union-find
  - weighted-union-find
  - minimum-spanning-tree
  - topological-sort
  - lis
  - binary-indexed-tree
  - bellman-ford
  - floyd-warshall
  - dijkstra
  - fast-io
  - support
  - acknowledgments
  