title: "競プロのための標準 C++"
summary: "◆ 内容\n競技プログラミングで使う C++ 標準機能を解説します。競技プログラミング独特のハックやスタイル（<bits/stdc++.h>, 大きな配列、using namespace std 等）を避け、一般の C++ ソフトウェア開発でも通用するコーディングの練習ができます。\n\n◆C++ バージョン\nC++20 / 23（AtCoder と同じ gcc 12.2）\n\n◆ 対象読者\n・競技プログラミング上達のために C++ の機能を一通り学びたい方\n・コンテスト中に参照できる C++ ドキュメントを探している方\n現在は APG4b や市販の入門書で C++ を学んだ人にとって有益な内容から書き始めています。将来はより幅広い内容を扱います\n\n◆ 本書へのご意見・ご提案\nhttps://github.com/Reputeless/Zenn.Public/issues \n全編無料公開ですが、購入してくれると筆が進みます。これまで 40 名以上の方が購入してくれました。ありがとうございます。\n\n◆ 著者の記事\n・『ゲーム開発者のための C++11〜C++20』（共著）\nhttps://zenn.dev/tetsurom/books/cpp11-cpp20-for-game-developers\n・『ゲーム開発者のための C++17〜C++23』（共著）\nhttps://zenn.dev/tetsurom/books/cpp17-cpp23-for-game-developers\n・競プロに便利な C++17 新機能まとめ\nhttps://qiita.com/Reputeless/items/db7dda0096f3ae91d450\n・競プロ典型 90 問 練習（C++17）https://github.com/Reputeless/tenkei_90\n・『冒険で学ぶ はじめてのプログラミング』（技術評論社）\nhttps://gihyo.jp/book/2018/978-4-7741-9918-4"
topics: ["cpp", "競プロ", "競技プログラミング", "atcoder"] # トピック（5つまで）
published: true # falseだと下書き
price: 1000
chapters:
  - main-function
  - comments
  - string
  - string-functions
  - vector
  - numeric
  - unordered_set
  - algorithm
  - library-tuple
  - library-ios-iomanip
  - union-find
  - weighted-union-find
  - minimum-spanning-tree
  - topological-sort
  - lis
  - binary-indexed-tree
  - bellman-ford
  - floyd-warshall
  - dijkstra
  - fast-io
  - support
  - acknowledgments
  - library-algorithm
  